package com.securacore.app.service;

import com.securacore.app.dto.QRVisitor.QRVisitorRequestDTO;
import com.securacore.app.dto.QRVisitor.QRVisitorResponseDTO;
import com.securacore.app.dto.QRVisitor.QRVisitorValidationDTO;
import com.securacore.app.entity.QRVisitor;
import com.securacore.app.repository.QRVisitorRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
public class QRVisitorService {
    
    @Autowired
    private QRVisitorRepository qrVisitorRepository;
    
    public QRVisitorResponseDTO createQRVisitor(QRVisitorRequestDTO request) {
        try {
            QRVisitor qrVisitor = new QRVisitor();
            qrVisitor.setName(request.getName());
            qrVisitor.setPurpose(request.getPurpose());
            qrVisitor.setVisitDate(request.getVisitDate() != null ? request.getVisitDate() : LocalDate.now());
            qrVisitor.setRelation(request.getRelation());
            qrVisitor.setFlatNo(request.getFlatNo());
            
            // Generate unique QR code
            String qrCode = "QR" + UUID.randomUUID().toString().substring(0, 8).toUpperCase();
            qrVisitor.setQrCode(qrCode);
            
            QRVisitor savedVisitor = qrVisitorRepository.save(qrVisitor);
            
            return new QRVisitorResponseDTO(
                savedVisitor.getId(),
                savedVisitor.getQrCode(),
                "QR Visitor created successfully",
                true
            );
        } catch (Exception e) {
            return new QRVisitorResponseDTO(0, "", "Failed to create QR visitor: " + e.getMessage(), false);
        }
    }
    
    public QRVisitorValidationDTO validateQRVisitor(Map<String, Object> qrData) {
        try {
            // Extract visitor ID from QR data
            Integer visitorId = (Integer) qrData.get("id");
            if (visitorId == null) {
                return new QRVisitorValidationDTO(false, "Invalid QR code: Missing visitor ID", null);
            }

            // Find visitor in database
            QRVisitor qrVisitor = qrVisitorRepository.findById(visitorId).orElse(null);
            if (qrVisitor == null) {
                return new QRVisitorValidationDTO(false, "QR Visitor not found in database", null);
            }

            // Check if visit is approved
            if (!"APPROVED".equals(qrVisitor.getStatus())) {
                return new QRVisitorValidationDTO(false, "Visit is not approved", null);
            }

            // Check if visit date matches today
            LocalDate today = LocalDate.now();
            if (qrVisitor.getVisitDate() != null && !qrVisitor.getVisitDate().equals(today)) {
                return new QRVisitorValidationDTO(false, "Visit is not scheduled for today", null);
            }

            // Check if visitor is already checked in
            if (qrVisitor.getCheckInTime() != null) {
                return new QRVisitorValidationDTO(false, "Visitor already checked in", null);
            }

            // Check if created by resident (QR-based visits)
            if (!qrVisitor.isCreatedByResident()) {
                return new QRVisitorValidationDTO(false, "Invalid QR code: Not generated by resident", null);
            }

            // All validations passed - create visitor data map
            Map<String, Object> visitorData = new HashMap<>();
            visitorData.put("id", qrVisitor.getId());
            visitorData.put("name", qrVisitor.getName());
            visitorData.put("purpose", qrVisitor.getPurpose());
            visitorData.put("visitDate", qrVisitor.getVisitDate());
            visitorData.put("relation", qrVisitor.getRelation());
            visitorData.put("flatNo", qrVisitor.getFlatNo());
            visitorData.put("status", qrVisitor.getStatus());
            visitorData.put("createdByResident", qrVisitor.isCreatedByResident());
            visitorData.put("qrCode", qrVisitor.getQrCode());

            return new QRVisitorValidationDTO(true, "QR Visitor validated successfully", visitorData);

        } catch (Exception e) {
            return new QRVisitorValidationDTO(false, "Error validating QR visitor: " + e.getMessage(), null);
        }
    }
    
    public String checkinQRVisitor(int visitorId) {
        try {
            QRVisitor qrVisitor = qrVisitorRepository.findById(visitorId).orElse(null);
            if (qrVisitor == null) {
                return "QR Visitor not found";
            }
            
            if (qrVisitor.getCheckInTime() != null) {
                return "QR Visitor already checked in";
            }
            
            qrVisitor.setCheckInTime(LocalDateTime.now());
            qrVisitorRepository.save(qrVisitor);
            
            return "QR Visitor checked in successfully";
        } catch (Exception e) {
            return "Error checking in QR visitor: " + e.getMessage();
        }
    }
    
    public String checkoutQRVisitor(int visitorId) {
        try {
            QRVisitor qrVisitor = qrVisitorRepository.findById(visitorId).orElse(null);
            if (qrVisitor == null) {
                return "QR Visitor not found";
            }
            
            if (qrVisitor.getCheckOutTime() != null) {
                return "QR Visitor already checked out";
            }
            
            qrVisitor.setCheckOutTime(LocalDateTime.now());
            qrVisitorRepository.save(qrVisitor);
            
            return "QR Visitor checked out successfully";
        } catch (Exception e) {
            return "Error checking out QR visitor: " + e.getMessage();
        }
    }

    public List<Map<String, Object>> getAllQRVisitors() {
        try {
            List<QRVisitor> visitors = qrVisitorRepository.findAll();
            return visitors.stream().map(this::convertToMap).collect(Collectors.toList());
        } catch (Exception e) {
            return List.of();
        }
    }

    public List<Map<String, Object>> getQRVisitorsByFlat(String flatNo) {
        try {
            List<QRVisitor> visitors = qrVisitorRepository.findByFlatNo(flatNo);
            return visitors.stream().map(this::convertToMap).collect(Collectors.toList());
        } catch (Exception e) {
            return List.of();
        }
    }

    public List<Map<String, Object>> getQRVisitorsByDate(LocalDate date) {
        try {
            List<QRVisitor> visitors = qrVisitorRepository.findByVisitDate(date);
            return visitors.stream().map(this::convertToMap).collect(Collectors.toList());
        } catch (Exception e) {
            return List.of();
        }
    }

    public List<Map<String, Object>> getQRVisitorsByFlatAndDate(String flatNo, LocalDate date) {
        try {
            List<QRVisitor> visitors = qrVisitorRepository.findByFlatNoAndVisitDate(flatNo, date);
            return visitors.stream().map(this::convertToMap).collect(Collectors.toList());
        } catch (Exception e) {
            return List.of();
        }
    }

    private Map<String, Object> convertToMap(QRVisitor visitor) {
        Map<String, Object> visitorMap = new HashMap<>();
        visitorMap.put("id", visitor.getId());
        visitorMap.put("name", visitor.getName());
        visitorMap.put("purpose", visitor.getPurpose());
        visitorMap.put("visitDate", visitor.getVisitDate());
        visitorMap.put("relation", visitor.getRelation());
        visitorMap.put("flatNo", visitor.getFlatNo());
        visitorMap.put("qrCode", visitor.getQrCode());
        visitorMap.put("status", visitor.getStatus());
        visitorMap.put("checkInTime", visitor.getCheckInTime());
        visitorMap.put("checkOutTime", visitor.getCheckOutTime());
        visitorMap.put("createdAt", visitor.getCreatedAt());
        visitorMap.put("createdByResident", visitor.isCreatedByResident());
        return visitorMap;
    }
}
